### ISSUE TITLE
Peer Review; voorgestelde aanpassingen

### ISSUE THREAD

**Issue by WesselSmit** [Choerd/functional-programming#4]
# Voorgestelde aanpassingen:
* schets kan iets meer hifi om werking beter uit te leggen
* volgorde van readme aanpassen; concept meer omhoog
* link naar gebruikte d3 voorbeelden
* API; leg uit wat er gebeurt met lege en invalid values
* .catch() toevoegen aan je async fetch function
* Wiki > data transforming pattern; leg uit wat elke functie doet, het proces moet stapsgewijs uitgelegd zijn en te volgen zijn voor iemand die niet jouw code kent (in tekst bedoel ik, niet in comments. comments lezen niet fijn en vallen vaak buiten beeld)
* data opschoon code patroon kan meer functional, denk aan meer dingen in variabelen declareren ipv te hardcoden

**Comment by Choerd** [comment]
- [x] schets kan iets meer hifi om werking beter uit te leggen
- [x] volgorde van readme aanpassen; concept meer omhoog
- [x] link naar gebruikte d3 voorbeelden
- [ ] .API; leg uit wat er gebeurt met lege en invalid values
- [x] .catch() toevoegen aan je async fetch function
- [ ] Wiki > data transforming pattern; leg uit wat elke functie doet, het proces moet stapsgewijs uitgelegd zijn en te volgen zijn voor iemand die niet jouw code kent (in tekst bedoel ik, niet in comments. comments lezen niet fijn en vallen vaak buiten beeld)
- [ ] data opschoon code patroon kan meer functional, denk aan meer dingen in variabelen declareren ipv te hardcoden
